fix: adding branch check

diff --git a/.husky/branch-check b/.husky/branch-check
--- a/.husky/branch-check
+++ b/.husky/branch-check
@@ -3,9 +3,12 @@
 
 echo "this hook is running 🔥🔥🔥🔥🔥🔥" 
 
-BRANCH=$(git rev-parse --abbrev-ref HEAD)
-
-if [ "$BRANCH" = "development" ]; then
-  echo "You are not allowed to commit changes directly to the development branch"
-  exit 1
+branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
+if [[ "$branch" == "master" ]] || [[ "$branch" == "development" ]] || [[ "$branch" == "qa" ]] 
+then
+    echo "cannot commit to major branches" 
+    exit 1 
+else 
+    echo "Running code tests... 🔥🔥🔥🔥" 
+    npm run lint
 fi
